### ISSUE TITLE
Repository in Organization Account

### ISSUE THREAD

**Issue by edsu** [samuelmeuli/action-electron-builder#22]
I guess this might be a question for electron-builder but I was wondering if you've ever seen a 404 error from the GitHub API come when this action attempts to *publish* for a repository in an Organization Account? Is it possible that the GITHUB_TOKEN that is generated automatically in actions does not have enough permissions to work with Organization repositories?

You can see my main.yml [here](https://github.com/DocNow/hydrator/blob/cdf26596a1cf0cd9052d3c16e7610963a5dc51c2/.github/workflows/main.yml) but it should look pretty familiar :-)

Thank you very much for this action by the way!

```
Will run Yarn commands in directory "."

Installing dependencies using Yarn…
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > connected-react-router@6.8.0" has unmet peer dependency "immutable@^3.8.1 || ^4.0.0-rc.1".
warning " > connected-react-router@6.8.0" has unmet peer dependency "seamless-immutable@^7.1.3".
warning " > styled-components@5.1.0" has unmet peer dependency "react-is@>= 16.8.0".
[4/4] Building fresh packages...
$ electron-builder install-app-deps
  • electron-builder  version=22.5.1
  • loaded configuration  file=/Users/runner/runners/2.169.0/work/hydrator/hydrator/electron-builder.yml
Done in 54.93s.

Running the build script…
Building the Electron app…
yarn run v1.22.4
$ /Users/runner/runners/2.169.0/work/hydrator/hydrator/node_modules/.bin/electron-builder --mac
  • electron-builder  version=22.5.1 os=19.4.0
  • artifacts will be published if draft release exists  reason=CI detected
  • loaded configuration  file=/Users/runner/runners/2.169.0/work/hydrator/hydrator/electron-builder.yml
  • packaging       platform=darwin arch=x64 electron=8.2.3 appOutDir=dist/mac
  • downloading     url=https://github.com/electron/electron/releases/download/v8.2.3/electron-v8.2.3-darwin-x64.zip size=66 MB parts=8
  • downloaded      url=https://github.com/electron/electron/releases/download/v8.2.3/electron-v8.2.3-darwin-x64.zip duration=1.134s
  • skipped macOS application code signing  reason=cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://electron.build/code-signing allIdentities=
                                                   0 identities found
                                              
                                                Valid identities only
                                                   0 valid identities found
  • building        target=DMG arch=x64 file=dist/Hydrator-0.0.4.dmg
  • building block map  blockMapFile=dist/Hydrator-0.0.4.dmg.blockmap
  • publishing      publisher=Github (owner: docnow, project: hdyrator, version: 0.0.4)
  • uploading       file=Hydrator-0.0.4.dmg.blockmap provider=GitHub
  ⨯ Cannot cleanup: 

Error #1 --------------------------------------------------------------------------------
HttpError: 404 Not Found
"method: GET url: https://api.github.com/repos/docnow/hdyrator/releases\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "server": "GitHub.com",
  "date": "Sat, 18 Apr 2020 09:38:57 GMT",
  "content-type": "application/json; charset=utf-8",
  "content-length": "124",
  "connection": "close",
  "status": "404 Not Found",
  "x-ratelimit-limit": "1000",
  "x-ratelimit-remaining": "996",
  "x-ratelimit-reset": "1587205272",
  "x-github-media-type": "github.v3; format=json",
  "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset",
  "access-control-allow-origin": "*",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "1; mode=block",
  "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
  "content-security-policy": "default-src 'none'",
  "vary": "Accept-Encoding, Accept, X-Requested-With",
  "x-github-request-id": "5ECA:5AA2:484874:7AD07E:5E9ACAB1"
}
    at createHttpError (/Users/runner/runners/2.169.0/work/hydrator/hydrator/node_modules/builder-util-runtime/src/httpExecutor.ts:30:10)
    at NodeHttpExecutor.handleResponse (/Users/runner/runners/2.169.0/work/hydrator/hydrator/node_modules/builder-util-runtime/src/httpExecutor.ts:131:14)
    at ClientRequest.<anonymous> (/Users/runner/runners/2.169.0/work/hydrator/hydrator/node_modules/builder-util-runtime/src/httpExecutor.ts:86:16)
    at Object.onceWrapper (events.js:417:26)
    at ClientRequest.emit (events.js:310:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:603:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:476:22)
    at TLSSocket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at TLSSocket.Readable.push (_stream_readable.js:209:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
```

**Comment by edsu** [comment]
Whoops, this was user error. I had a typo for the repository url in my package.json! This comment helped me diagnose:

https://github.com/electron-userland/electron-builder/issues/325#issuecomment-211917950
