### ISSUE TITLE
"electron-builder install-app-deps" get a error

### ISSUE THREAD

**Issue by boyphongsakorn** [samuelmeuli/action-electron-builder#56]
`Will run NPM commands in directory "."

Installing dependencies using NPM…

> fpsmember@1.4.0 postinstall /home/runner/work/fpsmember/fpsmember
> electron-builder install-app-deps

  • electron-builder  version=22.9.1
  • loaded configuration  file=package.json ("build" field)
  ⨯ spawn /home/runner/work/fpsmember/fpsmember/node_modules/app-builder-bin/linux/x64/app-builder EACCES  stackTrace=
                                                                                                             Error: spawn /home/runner/work/fpsmember/fpsmember/node_modules/app-builder-bin/linux/x64/app-builder EACCES
                                                                                                                 at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
                                                                                                                 at onErrorNT (internal/child_process.js:415:16)
                                                                                                                 at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fpsmember@1.4.0 postinstall: `electron-builder install-app-deps`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fpsmember@1.4.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-02-02T05_42_50_123Z-debug.log
child_process.js:660
    throw err;
    ^

Error: Command failed: npm install
    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at run (/home/runner/work/_actions/samuelmeuli/action-electron-builder/v1/index.js:21:27)
    at runAction (/home/runner/work/_actions/samuelmeuli/action-electron-builder/v1/index.js:109:2)
    at Object.<anonymous> (/home/runner/work/_actions/samuelmeuli/action-electron-builder/v1/index.js:150:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 12054,
  stdout: null,
  stderr: null
}`

**Comment by kaiserdj** [comment]
I don't know why it gives that error, but if you lower the version of "electron-builder" to "22.10.5". It will work

At least it works for me
