### ISSUE TITLE
ERR_ELECTRON_BUILDER_CANNOT_EXECUTE

### ISSUE THREAD

**Issue by jarrodek** [samuelmeuli/action-electron-builder#58]
I am trying to configure then GH action and after a few hours, I am starting to giving up.

My repo is private but I believe I already fixed all issues related to access tokens. Dependencies are installed, build performed, but the publish action fails. I have a build that releases the app for Windows, Linux, and macOS. It always fils on Linux as it's faster than other platforms.

The action produces the following output (I am replacing GH org with xxx and repo name with yyy because it is a private repo of my organization):

```
Running the build script…

Building and releasing the Electron app…
  • electron-builder  version=22.9.1 os=5.4.0-1039-azure
  • loaded configuration  file=package.json ("build" field)
  • author is missed in the package.json  appPackageFile=/home/runner/work/yyy/yyy/package.json
  • packaging       platform=linux arch=x64 electron=11.2.3 appOutDir=dist/linux-unpacked
  • downloading     url=https://github.com/electron/electron/releases/download/v11.2.3/electron-v11.2.3-linux-x64.zip size=76 MB parts=4
  • downloaded      url=https://github.com/electron/electron/releases/download/v11.2.3/electron-v11.2.3-linux-x64.zip duration=272ms
  • building        target=snap arch=x64 file=dist/domain-modeling-0.1.0-amd64.snap
  • building        target=AppImage arch=x64 file=dist/domain-modeling-0.1.0-x86_64.AppImage
  ⨯ expected argument for flag '--executable'  
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-12.0.1/appimage-12.0.1.7z size=1.6 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-12.0.1/appimage-12.0.1.7z duration=207ms
  ⨯ /home/runner/work/yyy/yyy/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=
                                                                                                                                                                             Error: /home/runner/work/yyy/yyy/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
                                                                                                                                                                                 at ChildProcess.<anonymous> (/home/runner/work/yyy/yyy/node_modules/builder-util/src/util.ts:243:14)
                                                                                                                                                                                 at Object.onceWrapper (node:events:485:26)
                                                                                                                                                                                 at ChildProcess.emit (node:events:378:20)
                                                                                                                                                                                 at maybeClose (node:internal/child_process:1067:16)
                                                                                                                                                                                 at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
  • publishing      publisher=Github (owner: xxx, project: yyy, version: 0.1.0)
  • uploading       file=[masked-for-privacy]-0.1.0-x86_64.AppImage provider=GitHub
npm ERR! code 1
npm ERR! path /home/runner/work/yyy/yyy
npm ERR! command failed
npm ERR! command sh -c electron-builder "--linux" "--publish" "always"

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-02-12T07_38_08_096Z-debug.log
/home/runner/work/_actions/samuelmeuli/action-electron-builder/v1/index.js:144
				throw err;
				^

Error: Command failed: npx --no-install electron-builder --linux --publish always 
    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at run (/home/runner/work/_actions/samuelmeuli/action-electron-builder/v1/index.js:21:27)
    at runAction (/home/runner/work/_actions/samuelmeuli/action-electron-builder/v1/index.js:132:4)
    at Object.<anonymous> (/home/runner/work/_actions/samuelmeuli/action-electron-builder/v1/index.js:150:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 2701,
  stdout: null,
  stderr: null
}
```

Any idea what that would be?

**Comment by abulka** [comment]
I'm getting this exact error too - though luckily there is a second action workflow that succeeds. 

Not sure why two actions workflows are triggered by a push to GitHub. This above error occurs on the workflow that is for the `main` branch. The one that succeeds is for the `vN.N.N` branch. 

I just followed the instructions in the README with a bare bones test project.
