### ISSUE TITLE
failing to build for linux

### ISSUE THREAD

**Issue by princemdavi** [samuelmeuli/action-electron-builder#78]
ubuntu-latest is not working. My electron app is not been built for linux but for windows and macos, everything is working well

**Comment by wildone** [comment]
any more info?

**Comment by patrick-motard** [comment]
I believe this is a duplicate of https://github.com/samuelmeuli/action-electron-builder/issues/58

I'm also running into this issue. There is no known workaround.

**Comment by Escaflownevan** [comment]
Same for me. 20 Days ago my latest release works perfect. Today i get an error in Linux. The log looks diffrent: 

 wine is required, please see https://electron.build/multi-platform-build#linux  \n' +
│      '  ⨯ /home/runner/work/crypTrax-Nuxt/crypTrax-Nuxt/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  failedTask=build stackTrace=Error: /home/runner/work/crypTrax-Nuxt/crypTrax-Nuxt/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE\n' +

All old working releases there's no line with 'wine is required'. I don't know if this helps

**Comment by Andreoew** [comment]
Hello I'm also getting error for linux, could someone give me a hint? Here is the error I get:

Error: Command failed: npx --no-install electron-builder --linux --publish always 

`
/home/runner/work/_actions/samuelmeuli/action-electron-builder/v1/index.js:144
				throw err;
				^

Error: Command failed: npx --no-install electron-builder --linux --publish always 
    at checkExecSyncError (child_process.js:635:11)
    at execSync (child_process.js:671:15)
    at run (/home/runner/work/_actions/samuelmeuli/action-electron-builder/v1/index.js:21:27)
    at runAction (/home/runner/work/_actions/samuelmeuli/action-electron-builder/v1/index.js:132:4)
    at Object.<anonymous> (/home/runner/work/_actions/samuelmeuli/action-electron-builder/v1/index.js:150:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 2[98](https://github.com/Andreoew/rotion/actions/runs/5317344429/jobs/9627775510#step:7:99)5,
  stdout: null,
  stderr: null

`
