### ISSUE TITLE
Application entry file "index.js" in the app.asar does not exist. Seems like a wrong configuration.

### ISSUE THREAD

**Issue by Jazcash** [samuelmeuli/action-electron-builder#80]
I can build locally on both windows and ubuntu, but am getting this error in CI.

```
Building and releasing the Electron app…
  • electron-builder  version=22.14.5 os=5.13.0-1022-azure
  • packaging       platform=linux arch=x64 electron=16.0.6 appOutDir=dist/linux-unpacked
  ⨯ Application entry file "index.js" in the "/home/runner/work/bar-lobby/bar-lobby/dist/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.  failedTask=build stackTrace=Error: Application entry file "index.js" in the "/home/runner/work/bar-lobby/bar-lobby/dist/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.
    at error (/home/runner/work/bar-lobby/bar-lobby/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:7:12)
    at Object.checkFileInArchive (/home/runner/work/bar-lobby/bar-lobby/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:31:11)
    at LinuxPackager.checkFileInPackage (/home/runner/work/bar-lobby/bar-lobby/node_modules/app-builder-lib/src/platformPackager.ts:501:7)
    at LinuxPackager.sanityCheckPackage (/home/runner/work/bar-lobby/bar-lobby/node_modules/app-builder-lib/src/platformPackager.ts:549:5)
    at LinuxPackager.doPack (/home/runner/work/bar-lobby/bar-lobby/node_modules/app-builder-lib/src/platformPackager.ts:310:5)
    at LinuxPackager.pack (/home/runner/work/bar-lobby/bar-lobby/node_modules/app-builder-lib/src/platformPackager.ts:[136](https://github.com/Jazcash/bar-lobby/runs/6263025656?check_suite_focus=true#step:4:136):5)
    at Packager.doBuild (/home/runner/work/bar-lobby/bar-lobby/node_modules/app-builder-lib/src/packager.ts:441:9)
    at Object.executeFinally (/home/runner/work/bar-lobby/bar-lobby/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/home/runner/work/bar-lobby/bar-lobby/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/home/runner/work/bar-lobby/bar-lobby/node_modules/app-builder-lib/src/packager.ts:337:12)
    at Object.executeFinally (/home/runner/work/bar-lobby/bar-lobby/node_modules/builder-util/src/promise.ts:12:14)
/home/runner/work/_actions/samuelmeuli/action-electron-builder/v1.6.0/index.js:144
				throw err;
```

After building on Ubuntu, I've unpacked the asar to confirm that index.js is there:

![image](https://user-images.githubusercontent.com/1434248/166314179-9c788845-c0dc-45fa-b046-e8d7cae3fb86.png)

My electronBuilder config in vue.config.js:

```
electronBuilder: {
    mainProcessFile: "src/main.ts",
    mainProcessWatch: ["src/main.ts", "src/main-window.ts"],
    rendererProcessFile: "src/render.ts",
    customFileProtocol: "bar://./",
    nodeIntegration: true,
    builderOptions: {
        productName: "BAR Lobby",
        directories: {
            buildResources: "build"
        },
        extraResources: [
            {
                "from": "resources",
                "to": ".",
                "filter": "**/*"
            }
        ],
        win: {
            target: ["nsis", "portable"],
        },
        nsis: {
            oneClick: false,
            perMachine: true,
            allowToChangeInstallationDirectory: true
        },
        linux: {
            target: ["AppImage"],
            category: "Game"
        },
        //publish: ["github"],
    },
    chainWebpackRendererProcess: config => {
        config.target("electron-renderer");
    }
},
```

Any ideas?

**Comment by Jazcash** [comment]
Nvm, was missing `use_vue_cli: true`

**Comment by timstrasser** [comment]
I have the same issue. I'm not sure how to fix it.
